version: 2
updates:
  # Python bağımlılıklarını devre dışı bırak
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    
  # npm bağımlılıklarını devre dışı bırak
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
